src/GoedBezigWebApp/Controllers/GroupController.cs
using System;
using System.Threading.Tasks;
using GoedBezigWebApp.Models;
using GoedBezigWebApp.Models.Exceptions;
using GoedBezigWebApp.Models.GroupViewModels;
using GoedBezigWebApp.Models.Repositories;
using GoedBezigWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using GoedBezigWebApp.Filters;
using GoedBezigWebApp.Models.GroupState;

namespace GoedBezigWebApp.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private readonly IGroupRepository _groupRepository;
        private readonly IUserRepository _userRepository;
        private readonly UserManager<User> _userManager;

        public GroupController(UserManager<User> userManager, IGroupRepository groupRepository, IUserRepository userRepository)
        {
            _groupRepository = groupRepository;
            _userRepository = userRepository;
            _userManager = userManager;
        }
        [ServiceFilter(typeof(UserFilter))]
        public IActionResult Index(User user)
        {
            if (user == null)
            {
                TempData["error"] = "User not logged in";
                return View();
            }
            else
            {
                //filter enkel de groepen:
                // van de organisatie waar de ingelogde user deel van uitmaakt => CHECK
                // die niet gesloten zijn => CHECK
                // met een motivatie die nog niet goegekeurd is 
                return View(_groupRepository.GetAll()
                    .Where(
                    (g => g.GbOrganization == user.Organization
                    && g.ClosedGroup == false
                    && !(g.GroupState is MotivationApprovedState))//wat is de status voor GOEDGEKEURD ?  
                ));
            }
        }
        [ServiceFilter(typeof(UserFilter))]
        public IActionResult Edit(string id, User user)
        {
            Group group = _groupRepository.GetBy(id);
            _groupRepository.LoadOrganizations(group);
            ViewBag.ExternalOrganization = group.ExternalOrganization;
            return View(new GroupEditViewModel(group));
        }

        [HttpPost]
        [ServiceFilter(typeof(UserFilter))]
        public IActionResult Edit(GroupEditViewModel groupEditViewModel, User user)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var group = _groupRepository.GetBy(groupEditViewModel.Name);
                    group.SaveMotivation(groupEditViewModel.Motivation);
                    group.GroupState.AddCompanyDetails(groupEditViewModel.CompanyName, groupEditViewModel.CompanyAddress, groupEditViewModel.CompanyEmail, groupEditViewModel.CompanyWebsite);
                    group.GroupState.AddCompanyContact(groupEditViewModel.CompanyContactName, groupEditViewModel.CompanyContactSurname, groupEditViewModel.CompanyContactEmail, groupEditViewModel.CompanyContactTitle);
                    _groupRepository.SaveChanges();
                    TempData["message"] = $"{user.UserName} De groep {group.GroupName} werd succesvol aangepast.";
                    return RedirectToAction(nameof(Index), "Home");

                }
                catch (GroupExistsException)
                {
                    TempData["error"] = $"Er bestaat al een groep met de naam {groupEditViewModel.Name}. Kies een andere naam";
                    groupEditViewModel.Name = null;
                }
                catch (MotivationException e)
                {

                    TempData["error"] = e.Message;
                }
                //catch (Exception)
                //{
                //    TempData["error"] = $"Er is iets fout gelopen. Groep {groupEditViewModel.Name} werd niet opgeslagen";
                //    groupEditViewModel.Name = null;
                //}

            }
            return View(nameof(Edit), groupEditViewModel);
        }

        [ServiceFilter(typeof(UserFilter))]
        public IActionResult Create(User user)
        {
            return View(nameof(Edit), new GroupEditViewModel(new Group()));
        }

        [HttpPost]
        [ServiceFilter(typeof(UserFilter))]

        public async Task<IActionResult> Create(GroupEditViewModel groupEditViewModel, User user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (_groupRepository.Present(groupEditViewModel.Name)) { throw new GroupExistsException(); }

                    Group group = user.Organization.AddGroup(groupEditViewModel.Name, user);
                    group.SaveMotivation(groupEditViewModel.Motivation);
                    group.AddCompanyDetails(groupEditViewModel.CompanyName, groupEditViewModel.CompanyAddress, groupEditViewModel.CompanyEmail, groupEditViewModel.CompanyWebsite);
                    group.AddCompanyContact(groupEditViewModel.CompanyContactName, groupEditViewModel.CompanyContactSurname, groupEditViewModel.CompanyContactEmail, groupEditViewModel.CompanyContactTitle);
                    _groupRepository.SaveChanges();
                    TempData["message"] = $"{user.UserName} De groep {group.GroupName} werd succesvol aangemaakt. U kan de groep nog bewerken om zaken aan te passen.";

                    //Mail notification to lector
                    //@Bart: waar vind ik de lector die bij het aanmaken van een groep onderstaande mail moet krijgen?

                    var mailer = new AuthMessageSender();
                    await mailer.SendEmailAsync("bartjevm@gmail.com",
                        "Group has been added",
                        String.Format("Hi Lector,\n\na group has been added to the GiveADay Platform called {0} has been created.\n\nKind regards,\nGiveADay Bot", group.GroupName),
                        String.Format("<p>Hi Lector,<p><p>a group has been added to the GiveADay Platform called {0} has been created.</p><p>Kind regards<br>GiveADay Bot</p>", group.GroupName));
                    return RedirectToAction(nameof(Index), "Home");

                }
                catch (GroupExistsException)
                {
                    TempData["error"] = $"Er bestaat al een groep met de naam {groupEditViewModel.Name}. Kies een andere naam";
                    groupEditViewModel.Name = null;
                }
                catch (MotivationException e)
                {

                    TempData["error"] = e.Message;
                }
                //catch (Exception)
                //{
                //    TempData["error"] = $"Er is iets fout gelopen. Groep {groupEditViewModel.Name} werd niet opgeslagen";
                //    groupEditViewModel.Name = null;
                //}

            }
            return View(nameof(Edit), groupEditViewModel);
        }
        [ServiceFilter(typeof(UserFilter))]
        public IActionResult SubmitMotivation(string id, User user)
        {
            ViewData[nameof(Group.GroupName)] = _groupRepository.GetBy(id).GroupName;
            return View();
        }

        [HttpPost, ActionName("SubmitMotivation")]
        [ServiceFilter(typeof(UserFilter))]
        public async Task<IActionResult> SubmitConfirmed(string id, User user)
        {
            GroupEditViewModel groupEditViewModel = null;
            Group group = null;

            if (ModelState.IsValid)
            {


                try
                {

                    group = _groupRepository.GetBy(id);
                    group.GroupState.SubmitMotivation();
                    _groupRepository.SaveChanges();
                    TempData["message"] = $"De motivatie van {group.GroupName} werd succesvol doorgestuurd.";

                    //Mail notification to lector
                    //@Bart: waar vind ik de lector die bij het aanmaken van een groep onderstaande mail moet krijgen?

                    var mailer = new AuthMessageSender();
                    await mailer.SendEmailAsync("bartjevm@gmail.com",
                        "Motivation has been submitted",
                        String.Format(
                            "Hi Lector,\n\na motivation has been added to group {0} of the GiveADay Platform.\n\nKind regards,\nGiveADay Bot",
                            group.GroupName),
                        String.Format(
                            "Hi Lector,<br><br>a motivation has been added to group {0} of the GiveADay Platform.<br><br>Kind regards,<br>GiveADay Bot",
                            group.GroupName));
                    return RedirectToAction("Index", "Home");

                }
                catch (MotivationException e)
                {

                    TempData["error"] = $"De motivatie werd niet ingediend. {e.Message}";
                    groupEditViewModel = new GroupEditViewModel(group);
                }
                //catch (Exception)
                //{
                //    TempData["error"] = $"Er is iets fout gelopen. Groep {groupEditViewModel.Name} werd niet opgeslagen";
                //    groupEditViewModel.Name = null;
                //}

            }
            return View(nameof(Edit), groupEditViewModel);
        }
        private async Task<User> GetCurrentUserAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            return user != null ? _userRepository.GetBy(user.UserName) : null;
        }
        public async Task<IActionResult> AddUser(String id)
        {
            var user = await GetCurrentUserAsync();
            _userRepository.LoadInvitations(user);

            if (user == null)
            {
                TempData["error"] = "User not logged in";
                return View("Error");
            }
            else if (user.Group != null)
            {
                TempData["error"] = "User already member of a group";

src/GoedBezigWebApp/Views/Shared/Sidebar.cshtml
@using Castle.Core.Internal
@using GoedBezigWebApp.Models.UserViewModels
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@{
    UserViewModel user = (UserViewModel)ViewData["User"];
}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->

        @if (!SignInManager.IsSignedIn(User))
        {
            <div class="user-panel">
                <p>Register or Log in</p>
                <a asp-area="" asp-controller="Account" asp-action="Register" class="btn btn-primary" role="button">
                    Registreren
                </a>
                <a asp-area="" asp-controller="Account" asp-action="Login" class="btn btn-primary" role="button">
                    Inloggen
                </a>
            </div>
        }

        else
        {
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="https://placehold.it/160x160" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>@user.FirstName @user.FamilyName</p>
                    <a asp-area="" asp-controller="Manage"><i class="fa fa-pencil text-primary"></i>Edit</a>
                </div>
            </div>


            <hr/>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header">MAIN NAVIGATION</li>
                <li>
                    <a asp-area="" asp-controller="Organization" asp-action="Index">
                        <i class="fa fa-building"></i> <span>Organisaties</span>
                    </a>
                </li>
                @if (!user.Organization.IsNullOrEmpty())//Alles hieronder wordt pas getoond als de gebruiker is geregistreerd bij een Organisatie
                {
                @if (user.Group.IsNullOrEmpty())
                {
                    <li>
                        <a asp-area="" asp-controller="Invitation" asp-action="Index">
                            <i class="fa fa-exchange"></i> <span>Uitnodigingen</span>
                            <span class="pull-right-container">
                        <small class="label pull-right bg-green">@user.NrOfInvitations</small>
                    </span>
                        </a>
                    </li>
                }
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-users"></i> <span>Groepen</span>
                            <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                        </a>
                        <ul class="treeview-menu">
                            @if (user.Group.IsNullOrEmpty())
                            {
                                <li class="active"><a asp-area="" asp-controller="Group" asp-action="Index"><i class="fa fa-circle-o"></i> Bekijk open groepen</a></li>
                                <li class="active"><a asp-area="" asp-controller="Group" asp-action="Create"><i class="fa fa-circle-o"></i> Maak een groep aan</a></li>
                            }
                            else
                            {
                                <li class="active"><a asp-area="" asp-controller="Group" asp-action="Edit" asp-route-id="@user.Group"><i class="fa fa-circle-o"></i> Bewerk groep</a></li>
                                <li class="active"><a asp-area="" asp-controller="User" asp-action="Index" asp-route-id="@user.Group"><i class="fa fa-circle-o"></i> Voeg Leden Toe</a></li>
                                <li class="active"><a asp-area="" asp-controller="Group" asp-action="SubmitMotivation" asp-route-id="@user.Group"><i class="fa fa-circle-o"></i>Motivatie Indienen</a></li>
                                <li class="active"><a asp-area="" asp-controller="ActivityEvent" asp-action="Index"><i class="fa fa-circle-o"></i>Evenementen</a></li>
                                <li class="active"><a asp-area="" asp-controller="ActivityTask" asp-action="Index"><i class="fa fa-circle-o"></i>Draaiboek</a></li>
                            }
                        </ul>
                    </li>
                }
                @*<li class="treeview">
        <a href="#">
            <i class="fa fa-files-o"></i>
            <span>treeview</span>
        </a>
        <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> treeview1</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i> treeview2</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i> treeview3</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i> treeview4</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-files-o"></i>
            <span>labels</span>
        </a>
        <ul class="treeview-menu">
            <li>
                <a href="#">
                    <i class="fa fa-circle-o"></i> label1
                    <span class="pull-right-container">
                    <span class="label label-primary pull-right">4</span>
                </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-circle-o"></i> label2
                    <span class="pull-right-container">
                    <small class="label pull-right bg-green">new</small>
                </span>
                </a>
            </li>

            <li>
                <a href="#">
                    <i class="fa fa-circle-o"></i> label3
                    <span class="pull-right-container">
                    <small class="label pull-right bg-yellow">12</small>
                </span>
                </a>
            </li>

            <li>
                <a href="#">
                    <i class="fa fa-circle-o"></i> label4
                    <span class="pull-right-container">
                    <small class="label pull-right bg-red">5</small>

                </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-circle-o"></i> multi label
                    <span class="pull-right-container">
                    <small class="label pull-right bg-yellow">12</small>
                    <small class="label pull-right bg-green">16</small>
                    <small class="label pull-right bg-red">5</small>

                </span>
                </a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-calendar"></i> <span>Calendar</span>
            <span class="pull-right-container">
            <small class="label pull-right bg-red">3</small>
            <small class="label pull-right bg-blue">17</small>
        </span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-envelope"></i> <span>Mailbox</span>
            <span class="pull-right-container">
            <small class="label pull-right bg-yellow">12</small>
            <small class="label pull-right bg-green">16</small>
            <small class="label pull-right bg-red">5</small>
        </span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-share"></i> <span>Multilevel</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            <li>
                <a href="#">
                    <i class="fa fa-circle-o"></i> Level One
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                    <li>
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Level Two
                            <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
        </ul>
    </li>
    <li class="header">LABELS</li>
    <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
    <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
    <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>*@
            </ul>
        }
    </section>
    <!-- /.sidebar -->
</aside>

src/GoedBezigWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.ApplicationInsights.AspNetCore
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoedBezigWebApp</title>

    <environment names="Development">

        <link href="~/css/gad.bundle.css" rel="stylesheet" />
        <link href="~/css/BootstrapAanvullingen.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://www.giveaday.be/assets/css/fille.css">
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/css/gad.bundle.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/css/BootstrapAanvullingen.css" rel="stylesheet" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>

    <div class="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-bars"></i>
                    </a>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="https://www.giveaday.be/design/img/logo.svg" alt="Give a Day logo" class="logo"></a>
                </div>
                <div class="navbar-collapse collapse">


                    <ul class="nav navbar-nav">
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link"><span>Home</span></a></li>
                        @*<li class="nav-item"><a asp-area="" asp-controller="Invitation" asp-action="Index" class="nav-link"><span>@Localizer["Invitation"]</span></a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Organization" asp-action="Index" class="nav-link"><span>@Localizer["Organizations"]</span></a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Group" asp-action="Index" class="nav-link"><span>@Localizer["GroupIndex"]</span></a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Group" asp-action="Create" class="nav-link"><span>@Localizer["NewGroup"]</span></a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="User" asp-action="Index" class="nav-link"><span>@Localizer["Users"]</span></a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="ActivityEvent" asp-action="Index" class="nav-link"><span>@Localizer["ActivityEvent"]</span></a></li>*@
                        <li class="nav-divider"></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span>Mijn account</span>
                            </a>
                            @await Html.PartialAsync("_LoginPartial")
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        @if (TempData["message"] != null)
            {
            <div class="alert alert-success" style="position: relative;top: 80px;">@TempData["message"]</div>
        }
        @if (TempData["error"] != null)
            {
            <div class="alert alert-danger" role="alert" style="position: relative;top: 80px;">
                <i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;
                <span class="sr-only">Error:</span>
                @TempData["error"]
            </div>
        }
        <div id="page-wrapper">
            @RenderBody()
            <hr />
        </div>
        <footer>
            <div class="row">
                <div class="col-sm-6">
                    <p>&copy; 2017 - GoedBezigWebapp</p>
                </div>
                <div class="col-sm-6 text-right">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
            </div>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">


        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">


        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>


    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/GoedBezigWebApp/Views/Shared/_pannel.cshtml
@{
}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - GoedBezigWebApp</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap-->
    @*<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />*@
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link href="~/lib/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/lib/AdminLTE/dist/css/skins/skin-blue-light.css" rel="stylesheet" />
    
    @RenderSection("styles", required: false)


    <!--Giva A Day Style-->
    <link href="~/css/gad.bundle.css" rel="stylesheet" />
    <link href="~/css/BootstrapAanvullingen.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://www.giveaday.be/assets/css/fille.css">
    <link href="~/css/site.css" rel="stylesheet" />

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    @*<a type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <i class="fa fa-bars"></i>
                        </a>*@
                    <a href="#" class="navbar-toggle" data-toggle="offcanvas">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-bars"></i>
                    </a>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="https://www.giveaday.be/design/img/logo.svg" alt="Give a Day logo" class="logo"></a>
                </div>
                <div class="navbar-collapse collapse">


                    <ul class="nav navbar-nav">
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link"><span>Home</span></a></li>
                        @*<li class="nav-item"><a asp-area="" asp-controller="Invitation" asp-action="Index" class="nav-link"><span>@Localizer["Invitation"]</span></a></li>
                            <li class="nav-item"><a asp-area="" asp-controller="Organization" asp-action="Index" class="nav-link"><span>@Localizer["Organizations"]</span></a></li>
                            <li class="nav-item"><a asp-area="" asp-controller="Group" asp-action="Index" class="nav-link"><span>@Localizer["GroupIndex"]</span></a></li>
                            <li class="nav-item"><a asp-area="" asp-controller="Group" asp-action="Create" class="nav-link"><span>@Localizer["NewGroup"]</span></a></li>
                            <li class="nav-item"><a asp-area="" asp-controller="User" asp-action="Index" class="nav-link"><span>@Localizer["Users"]</span></a></li>
                            <li class="nav-item"><a asp-area="" asp-controller="ActivityEvent" asp-action="Index" class="nav-link"><span>@Localizer["ActivityEvent"]</span></a></li>*@
                        <li class="nav-divider"></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span>Mijn account</span>
                            </a>
                            @await Html.PartialAsync("_LoginPartial")
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
        @await Html.PartialAsync("Sidebar")
        <div class="content-wrapper">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @if (TempData["error"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    <i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;
                    <span class="sr-only">Error:</span>
                    @TempData["error"]
                </div>
            }
            <!-- Content Header (Page header) -->
            <section class="content-header">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            <div class="col-sm-6">
                <p>&copy; 2017 - GoedBezigWebapp</p>
            </div>
            <div class="col-sm-6 text-right">
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/app.js"></script>
    <script src="~/js/site.js" asp-append-version="true">
    </script>
    @RenderSection("scripts", required: false)

</body>
</html>