src/GoedBezigWebApp/Models/Organization.cs
namespace GoedBezigWebApp.Models
{
    public abstract class Organization
    {

        public int OrgId { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Btw { get; set; }
        public string Description { get; set; }

        public int? AddressId { get; set; }
        public OrganizationalAddress Address { get; set; }

    }
}

src/GoedBezigWebApp/Models/OrganizationViewModels/OrganizationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoedBezigWebApp.Models.OrganizationViewModels
{
    public class OrganizationViewModel
    {
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Description { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public bool IsExternal { get; set; }
        public bool HasLabel { get; set; }
        public string Motivation { get; set; }


        public OrganizationViewModel()
        {
            
        }

        public OrganizationViewModel(Organization organization)
        {
            Name = organization.Name;
            Logo = organization.Logo;
            Description = organization.Description;
            AddressLine1 = organization.Address.AddressLine1;
            AddressLine2 = organization.Address.AddressPostalCode + " " + organization.Address.AddressCountry;
            IsExternal = organization is ExternalOrganization;
        }

        public OrganizationViewModel(ExternalOrganization organization, string motivation) : this(organization)
        {
            HasLabel = organization.HasGbLabel;
            Motivation = motivation;
        }
    }
}

src/GoedBezigWebApp/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Castle.Core.Internal;
using GoedBezigWebApp.Filters;
using GoedBezigWebApp.Models;
using GoedBezigWebApp.Models.Exceptions;
using GoedBezigWebApp.Models.OrganizationViewModels;
using GoedBezigWebApp.Models.Repositories;
using GoedBezigWebApp.Models.UserViewModels;
using GoedBezigWebApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace GoedBezigWebApp.Controllers
{
    [Authorize]
    [ServiceFilter(typeof(UserFilter))]
    public class OrganizationController : Controller
    {
        private readonly IOrganizationRepository _organizationRepository;
        private readonly IUserRepository _userRepository;
        private readonly UserManager<User> _userManager;
        private readonly IGroupRepository _groupRepository;

        public OrganizationController(UserManager<User> userManager, IOrganizationRepository organizationRepository,
            IUserRepository userRepository, IGroupRepository groupRepository)
        {
            _userManager = userManager;
            _organizationRepository = organizationRepository;
            _userRepository = userRepository;
            _groupRepository = groupRepository;
        }

        public IActionResult Index(String searchName, String searchLocation, bool isExternalWithLabel, bool isExternalWithoutLabel, string groupId, User user)
        {
            ViewData["searchName"] = searchName;
            ViewData["searchLocation"] = searchLocation;

            if (groupId.IsNullOrEmpty() && !isExternalWithLabel && !isExternalWithoutLabel)
            {
                //Load only gb-orgs
                ViewData["title"] = "GB Organizations";
                ViewBag.Cities = _organizationRepository.GetAllGbUniqueCities();
                return View(_organizationRepository.GetAllGbFilteredByNameAndLocation(searchName, searchLocation));
            }

            if (groupId.IsNullOrEmpty() && isExternalWithLabel && !isExternalWithoutLabel)
            {
                //Load only external orgs with Label
                ViewData["title"] = "External Organizations with GBLabel";
                ViewBag.isExternalWithLabel = true;
                ViewBag.Cities = _organizationRepository.GetAllExternalWithLabelUniqueCities();
                return View(_organizationRepository.GetAllExternalWithLabelFilteredByNameAndLocation(searchName, searchLocation));
            }

            if (groupId.IsNullOrEmpty() && !isExternalWithLabel && isExternalWithoutLabel)
            {
                //Load only external orgs without label
                ViewData["title"] = "External Organizations without GBLabel";
                ViewBag.isExternalWithoutLabel = true;
                ViewBag.Cities = _organizationRepository.GetAllExternalWithoutLabelUniqueCities();
                return View(_organizationRepository.GetAllExternalWithoutLabelFilteredByNameAndLocation(searchName, searchLocation));
            }

            else if (!groupId.IsNullOrEmpty() && checkEntitledToGiveGBLabel(groupId))
            {
                //Load only external orgs without label - ready to give label
                ViewData["title"] = "Give GBLabel to External Organization";
                ViewBag.Group = _groupRepository.GetBy(groupId);
                ViewBag.Cities = _organizationRepository.GetAllExternalWithoutLabelUniqueCities();
                return View(_organizationRepository.GetAllExternalWithoutLabelFilteredByNameAndLocation(searchName, searchLocation));
            }
            else
            {
                TempData["error"] =
                    "The request is not valid or the GroupId is either not valid or the group is not entitled to give a GBLabel to an organization.";
                return View("Error");
            }

        }
        
        public IActionResult Register(User user, int id = 0)
        {
            if (id == 0)
            {
                return View("Error");
            }

            try
            {
                _userRepository.GetBy(user.UserName).RegisterInOrganization(_organizationRepository.GetGbOrganizationBy(id));
                _userRepository.SaveChanges();
                TempData["message"] = $"You have been added to the organization succesfully!";
                return RedirectToAction("Index", "Home");
            }
            catch (OrganizationException error)
            {
                TempData["error"] = error.Message;
                return RedirectToAction("Index");
            }
        }
        
        public IActionResult AssignGBLabel(int id, string groupId, User user)
        {
            if (id == 0 || groupId.IsNullOrEmpty() || !checkEntitledToGiveGBLabel(groupId))
            {
                return View("Error");
            }

            ViewBag.Group = _groupRepository.GetBy(groupId);
            return View(_organizationRepository.GetExternalOrganizationBy(id));
        }

        [HttpPost]
        public IActionResult AssignGBLabel(int id, string groupId, List<ContactRecord> notifyContacts, User user)
        {
            if (id == 0 || groupId.IsNullOrEmpty() || !checkEntitledToGiveGBLabel(groupId))
            {
                TempData["error"] =
                    "The request is not valid or the GroupId is either not valid or the group is not entitled to give a GBLabel to an organization.";
                return View("Error");
            }

            try
            {
                _organizationRepository.GetExternalOrganizationBy(id).AssignGbLabel(_groupRepository.GetBy(groupId), notifyContacts);
                _organizationRepository.SaveChanges();
                TempData["message"] = "The organization has succesfully been given a GB label, the selected stakeholders have been contacted.";
            }

            catch (OrganizationException error)
            {
                TempData["error"] = error.Message;
                return RedirectToAction("AssignGBLabel", new { id = id, groupId = groupId });
            }

            return RedirectToAction("Edit", "Group", new { id = groupId });
        }

        private bool checkEntitledToGiveGBLabel(string groupId)
        {
            var group = _groupRepository.GetBy(groupId);
            _groupRepository.LoadOrganizations(group);
            _groupRepository.LoadUsers(group);
            return group.EntitledToGiveGbLabel();
        }

        public IActionResult View(int id)
        {
            var organization = _organizationRepository.GetById(id);

            if (organization == null)
            {
                TempData["error"] = "Organization does not exist";
            }

            var externalOrganization = organization as ExternalOrganization;

            // Check if organization is external and is assigned a GB label
            if (externalOrganization == null || !externalOrganization.HasGbLabel)
                return View(new OrganizationViewModel(organization));

            // Get motivation from group that invited this organization
            var group = _groupRepository.GetBy(externalOrganization);

            // TODO check motivation state == published

            return View(new OrganizationViewModel(externalOrganization, @group?.Motivation));
        }
    }
}

src/GoedBezigWebApp/Views/Organization/AssignGBLabel.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model GoedBezigWebApp.Models.ExternalOrganization

@{
    Layout = "~/Views/Shared/_pannel.cshtml";
}

@{
    ViewData["Title"] = "Give a GB Label to an Organization";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="AssignGBLabel">
    <div class="form-horizontal">
        <h4>Organization @Model.Name</h4>
        <p>@Localizer["Great to see that you want to add the GB Label to this organization. As soon as you confirm that this organization will get the GB-label, a confirmation email is sent to one or multiple contacts in this organization. Please select these contacts below."]</p>
        <table class="table">
            @for (int i = 0; i < Model.Contacts.Count(); i++)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="notifyContacts[@i].Selected" value="true"/>
                        <input name="notifyContacts[@i].ContactId" type="hidden" value="@Model.Contacts[i].ContactId" />
                        <input name="notifyContacts[@i].Email" type="hidden" value="@Model.Contacts[i].Email" />
                    </td>
                    <td>@Model.Contacts[i].Voornaam @Model.Contacts[i].Naam</td>
                    <td>@Model.Contacts[i].Functie</td>
                    <td>@Model.Contacts[i].Email</td>
                </tr>
            }
        </table>

        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @if (Model.Contacts.Count > 0)
                {
                    <input name="id" type="hidden" value="@Model.OrgId" />
                    <input name="groupId" type="hidden" value="@ViewBag.Group.GroupName" />
                    <input type="submit" value="@Localizer["Confirm GB-label and send email(s)"]" class="btn btn-default"/>
                }
                else
                {
                    <p style="color: red;">@Localizer["Assigning the GB-Label to this organization is not yet possible. Please ask the organization to register one or multiple contacts for their organization."]</p>
                }
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index", "Organization", new { groupId = ViewBag.Group.GroupName })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/GoedBezigWebApp/Views/Organization/Index.cshtml
@using Castle.Core.Internal
@using GoedBezigWebApp.Models.UserViewModels
@model IEnumerable<GoedBezigWebApp.Models.Organization>

@{
    Layout = "~/Views/Shared/_pannel.cshtml";
    UserViewModel user = (UserViewModel)ViewData["User"];
}

<h2>@ViewData["title"]</h2>
<hr />
@if (!user.Organization.IsNullOrEmpty())
{
    <p class="importantMsg">You are currently part of the Organization "@user.Organization"!</p>
}
<style>

    .organizationTable img {
        max-width: 100px;
        max-height: 100px;
    }
</style>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search name: <input type="text" name="searchName" value="@ViewData["searchName"]" />
            Search location: <select name="searchLocation" asp-for="@ViewData["searchLocation"]" asp-items="ViewBag.Cities">
                <option value="">---Select a city---</option>
            </select>
            @if (ViewBag.Group != null)
            {
                <input name="groupId" type="hidden" value="@ViewBag.Group.GroupName"/>
            }
            <input type="submit" value="Search" class="btn btn-default" />
            @if (ViewBag.Group == null)
            {
                <br />
                <a asp-action="Index">All GB Organizations</a><span> | </span>
                @Html.ActionLink("Ext. With Label", "Index", "Organization", new { isExternalWithLabel = true }) <span> | </span>
                @Html.ActionLink("Ext. Without Label", "Index", "Organization", new { isExternalWithoutLabel = true })

            }
        </p>
    </div>
</form>

<table class="table table-hover organizationTable">
    <thead>
    <tr>
        <th>
                
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*            <th>*@
        @*                @Html.DisplayNameFor(model => model.Description)*@
        @*            </th>*@
        <th>
            Address
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            @{
                var viewLink = "Organization/View/" + item.OrgId;
            }
            <td class="clickable-cell" data-href="@viewLink">
                <img src="@Html.DisplayFor(modelItem => item.Logo)" alt="@item.Name"/>
            </td>
            <td class="clickable-cell" data-href="@viewLink">
                @Html.DisplayFor(i => item.Name)
            </td>
            @*            <td>*@
            @*                @Html.DisplayFor(modelItem => item.Description)*@
            @*            </td>*@
            <td class="clickable-cell" data-href="@viewLink">
                @Html.DisplayFor(modelItem => item.Address.AddressLine1)<br/>
                @Html.DisplayFor(modelItem => item.Address.AddressPostalCode) @Html.DisplayFor(modelItem => item.Address.AddressCountry)<br/>
                @Html.DisplayFor(modelItem => item.Address.AddressCountry)
            </td>
            <td>
                @if (user.Organization.IsNullOrEmpty() && ViewBag.Group == null && ViewBag.isExternalWithLabel != true && ViewBag.isExternalWithoutLabel != true)
                {
                    @Html.ActionLink("Register", "Register", new {id = item.OrgId})
                }

                @if (ViewBag.Group != null)
                {
                    @Html.ActionLink("Assign GB Label", "AssignGBLabel", new {id = item.OrgId, groupId = ViewBag.Group.GroupName})
                }

            </td>
        </tr>
    }
    </tbody>
</table>
    
@section scripts
{
    <script>
        jQuery(document).ready(function ($) {
            $('.clickable-cell').click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
}

src/GoedBezigWebApp/Views/Organization/View.cshtml
@using GoedBezigWebApp.Models.OrganizationViewModels
@model GoedBezigWebApp.Models.OrganizationViewModels.OrganizationViewModel

@{
    Layout = "_pannel";
}
<!-- Header -->
<div class="media">
    <div class="media-left media-middle">
        <img class="media-object" style="width: 64px; height: 64px; object-fit: scale-down;" src="@Model.Logo" alt="@Model.Name" />
    </div>
    <div class="media-body" style="vertical-align: bottom;">
        <h2 style="margin-bottom: 0;">
            @Model.Name
            @if (!Model.IsExternal || Model.HasLabel)
            {
                <span class="text-success fa fa-check" data-toggle="tooltip" data-placement="right" title="Goed bezig!"></span>
            }
        </h2>
    </div>
</div>
<hr />

<!-- Details -->
<div class="row">
    <div class="col-md-8">
        <h4>About</h4>
        <p>@Model.Description</p>
        @* Show motivation if existing *@
        @if (Model.Motivation != null)
        {
            <!-- Motivation -->
            <h4>Motivation</h4>
            <p>@Model.Motivation</p>
        }

    </div>
    <div class="col-md-4">
        <h4>Address</h4>
        <address>
            @Model.AddressLine1 <br />
            @Model.AddressLine2
        </address>
    </div>
</div>